### ISSUE TITLE
Memory leak in training loop

### ISSUE THREAD

**Issue by david-waterworth** [BatsResearch/labelmodels#4]
It looks like you have a leak in the training loop

https://github.com/BatsResearch/labelmodels/blob/3b5683bef7ee902dc205a8cd93572b05b88dbad5/labelmodels/label_model.py#L90

You're holding on to the graph for each batch per epoch, since `running_loss` is the sum of non-detached tensors. For a large enough training set my GPU runs out of memory (the python process simply exit with no exception method).

It should be sufficient to change to

    running_loss += loss.item()

Doing this prevents the GPU memory use from increasing per step.

**Comment by stephenbach** [comment]
Ah, good catch. Thanks! Will merge into master as soon as tests pass.
